= 同构

https://zh.wikipedia.org/wiki/%E9%80%BB%E8%BE%91%E7%AC%A6%E5%8F%B7%E8%A1%A8[逻辑符号表]
https://zh.wikipedia.org/wiki/%E6%95%B0%E5%AD%A6%E7%AC%A6%E5%8F%B7%E8%A1%A8[数学符号表]

:math:
:stem: latexmath

== Equations in normal blocks

[latexmath]
++++
k_{n+1} = n^2 + k_n^2 - k_{n-1}
++++

Some useful text! Formula for quadratic root:

[stem]
++++
x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
++++

Inline equation works too! latexmath:[a^2+b^2=c^2]. Or as stem
stem:[a^2+b^2=c^2]. Pretty nice, huh?

== Equations in table cells

Equations in asciidoc style table cells work, too!

[%header]
|===
| Demo | Contents
| Inline Equation in *Asciidoc* Cells
a|

This is an *inline* equation: latexmath:[a^2+b^2=c^2].

| Block Equation in *Asciidoc* Cells
a| The following is a stem block:
[stem]
++++
a^2+b^2=c^2+d^2
++++

| Inline Equation in *Normal* Cell
| This is an *inline* equation: latexmath:[a^2+b^2=c^2].

| Inline Equation in *Header* Cell
h| This is an *inline* equation: latexmath:[a^2+b^2=c^2].

| Inline Equation in *Emphasis* Cell
e| This is an *inline* equation: latexmath:[a^2+b^2=c^2].

| Inline Equation in *Monospaced* Cell
m| This is an *inline* equation: latexmath:[a^2+b^2=c^2].

| Inline Equation in *Strong* Cell
s| This is an *inline* equation: latexmath:[a^2+b^2=c^2].

| Inline Equation in *Verse* Cell
v| This is an *inline* equation: latexmath:[a^2+b^2=c^2].

| Inline Equation in *Literal* Cell
l| This is an *inline* equation: latexmath:[a^2+b^2=c^2].

|===

== Equations in section titles

=== Proof of stem:[a^2+b^2=c^2]

==== Proof of stem:[a^2+b^2=c^2]
