= Taskwarrior

== 什么是Taskwarrior？

Taskwarrior在你的终端下管理你的待办列表。
它灵活、快速、高效、和谐，的完成其工作。

Taskwarrior可以扩展适合你的工作流。
将其用作一个掌管你任务，显示其列表，及从中移除任务的简单应用。
但是利用其功能，可以让其成为一种复杂的数据查询工具，这可以帮助你保持秩序，并顺利完成你的任务。

Taskwarrior是一个活跃的项目，我们每天都为其修复其Bug，改进和添加新特性。


== 为什么选择Taskwarrior？

五个选择Taskwarrior的好理由

1. 作为一个命令行用户你是否在寻找一种和谐、灵活、快速、高效的工具来轻松管理你的任务列表？
Taskwarrior被设计为低摩擦度，允许你来捕获细节，并重新返回你的工作。
+
[source, bash]
----
$ task add Prepare the first draft of the proposal due:friday
----
+
Taskwarrior使用自然而有表现力的命令行语法。

2. Taskwarrior是方法论中立的。
无论你遵循 http://gettingthingsdone.com/[GTD]，还是使用 http://pomodorotechnique.com/[番茄工作法]，或者做任何对你有用的事，Taskwarrior提供能力来帮助你，而不限制你。

+
3. Taskwarrior有一个活跃且友好的社区，提供对新老用户的各式帮助。
https://taskwarrior.org/support[从这里]获取支持选项列表。
需要立即得到答案 - 查看man或者 https://taskwarrior.org/docs[在线文档]
要提一些问题？
试试freenode上的#taskwarrior IRC。

+
4. Taskwarrior以尽可能多的方式打开：
* 它免费，并以MIT协议开放源代码。
* 它使用人类可读的文本文件储存数据，它导入和导出JSON，因此您的数据永远不会被俘虏。
* 拥有DOM访问和Hook脚本API。
* 有许多可用的免费和开放扩展脚本。
* Vit，一个基于curses的UI。
* FreeCinc，一个在线免费同步服务。
* Inthe.AM，一个免费的在线同步服务，Web界面和iOS客户端。
* BugWarrior，因此你可以从众多不同的Bug管理系统中导入你的漏洞issue。

+
5. Taskwarrior活跃且充满活力的项目。
在过去的一年，我们每天合并5.58个修改。
Taskwarrior得到了许多贡献者的热烈参与，目前有60人提供代码补丁。
但还有更多贡献者(其中252位)在文档、Bug、支持、主意、请求和扩展方面提供了帮助。
它只会变得越来越好。

== 快速演示

让我们看一看Taskwarrior的实际使用。
首先我们添加一些任务到我们的列表中。

[source, bahs]
----
$ task add Buy milk
Created task 1.

$ task add Buy eggs
Created task 2.

$ task add Bake cake
Created task 3.
----

现在让我们来看一下任务列表。

[source, bash]
----
$ task list

ID Description
-- -----------
1  Buy milk
2  Buy eggs
3  Bake cake

3 tasks.
----

假设我们购买了食材并希望标记前两个任务为完成。

[source, bash]
----
$ task 1 done
$ task 2 done
$ task list

ID Description
-- -----------
1  Bake cake

1 task.
----

这些是其前三个功能， 既 `add` 、 `list` 、 `done` 这三个命令，但这就是你可以开始使用Taskwarrior所需要知道的所有知识了。

但还有数百种其他功能，因此你了解更多就可以做的更多。
这完全取决你如何使用Taskwarrior：遵循上述的三个简单命令，或者了解复杂的筛选或者了解复杂的过滤器、自定义报告、用户定义元数据、颜色规则、Hook脚本、同步等。
