= 原始类型

*原始类型* 是没有任何类型参数的范型类或接口的名称。
例如，我们有如下范型类 `Box` :

[source, java]
----
public class Box<T> {
    public void set(T t) { /* ... */ }
    // ...
}
----

要创建 `Box<T>` 的参数化类型，你需要为形式类型参数 `T` 提供实际的参数：

[source, java]
----
Box<Integer> intBox = new Box<>();
----

如果省略实际类型参数，那么你创建了一个 `Box<T>` 的原始类型：

[source, java]
----
Box intBox = new Box();
----

所以， `Box` 是范型类型 `Box<T>` 的原始类型。
但是，不无范型的类或接口并不是原始类型。

原始类型出现在遗留代码中是因为许多 API 类（例如Collections)在 JDK 5.0 之前不是范型的。
使用原始类型时，您基本上会获得pre-generics行为——一个 Box 为您提供Object。
为了向后兼容，允许将参数化类型分配给它的原始类型：
[source, java]
----
Box<String> stringBox = new Box<>();
Box rawBox = stringBox;               // OK
----

但如果你非配一个原始类型到一个参数化类型，你将会得到警告。
[source, java]
----
Box rawBox = new Box();           // rawBox is a raw type of Box<T>
Box<Integer> intBox = rawBox;     // warning: unchecked conversion
----

如果你使用原始类型调用相应范型类中定义的范型方法，也会收到警告:
[source, java]
----
Box<String> stringBox = new Box<>();
Box rawBox = stringBox;
rawBox.set(8); // warning: unchecked invoation to set(T)
----

警告显示原始类型绕过了范型类型检查，将不安全代码的捕获推迟到了运行时。
因此，你应该避免使用原始类型。

https://docs.oracle.com/javase/tutorial/java/generics/erasure.html[类型擦除] 部分部分提供哦你了更多有关Java编译器如何使用原始类型的信息。

== 未检查的错误消息

正如之前所述，当将遗留代码和范型代码混合时，你可能会遇到如下警告消息：
[source]
----
Note: Example.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
----

使用对原始类型进行操作的旧 API 时可能会发生这种情况，如下例所示： 
[source]
----
public class WarningDemo {
    public static void main(String[] args){
        Box<Integer> bi;
        bi = createBox();
    }

    static Box createBox(){
        return new Box();
    }
}
----

术语“未检查”意味着编译器没有足够的类型信息来执行确保类型安全所需的所有类型检查。默认情况下，“unchecked”警告是禁用的，尽管编译器会给出提示。 要查看所有“未检查”警告，请使用 -Xlint:unchecked 重新编译。 

使用 -Xlint:unchecked 重新编译前面的示例会显示以下附加信息：

WarningDemo.java:4: warning: [unchecked] unchecked conversion
found   : Box
required: Box<java.lang.Integer>
        bi = createBox();
                      ^
1 warning

要完全禁用未经检查的警告，请使用 -Xlint:-unchecked 标志。 @SuppressWarnings("unchecked") 注释抑制未经检查的警告。 如果您不熟悉 @SuppressWarnings 语法，请参阅注解。
