== 授权学院简介

*授权学院* 是一系列介绍如何将授权集成到你的应用中的技术指南，
包括架构、建模模式、实施、测试及在 UI 层集成等等。
在完成此指南后，你将会拥有一个关于授权如何工作的心智模型
以及可以自行集成到应用中的相关工具。

如果你和大多数开发团队一样，你只想在授权上花费该花的时间 —— 而不是更多时间。
但问题是：关于如何集成授权到你应用的具体材料有限。
为了帮助开发人员构建这类系统及特性，我们建立了授权学院。

为了让课程尽可能真实，我们在整套课程中使用了一个名为 GitClub 的应用。
GitClub 是一个用来进行源代码托管、写作及版本控制的网站。
这听起来应该很熟悉！
我们对于 GitClub 的灵感来自与真实世界的应用 —— GitHub 和 GitLab —— 
他们都是通用授权场景的优秀研究案例。

本教程聚焦于企业对企业（B2B）软件即服务（SaaS）应用，但我们还是会在此过程中涵盖其他模式和模型。
所有层级的开发人员都会发现该课程很有用。
对于初级开发者，本课程将会为你建立起坚实的授权基础知识。
对于更有开发经验的老兵，该课程将为他们过去可能遇到的问题提供一种更简洁的方法。

我们是授权相关专业人员。
我们根据自己编写授权系统的经验以
及和从初创公司到财富 100 强等公司从事授权工作的开发人员进行了数十次会议，
构建了这门课程。

== 授权学院都教授什么内容？

这些内容被分为几个章节，其中涵盖以下内容：

* 第二章：什么是授权：如何组织你的授权代码
* 第三章：基于角色的访问控制：将你应用中的权限分组为像“用户”和“管理员”这样的角色
* 第四章：基于关系的权限控制：将权限按照像“文章的创建者可以编辑文章”这样的关系进行分组
* 第五章：认证的施行：一旦你的应用决定了允许后拒绝访问，你应该如何处理此决定？

我们正在筹划未来的一些章节：

* 用户接口
* 测试你的授权代码
* 跨微服务授权


接下来我们将定义授权本身并提供一个关于如何构建你的认证系统的综述。
在您阅读本指南时，我们鼓励您加入 https://join-slack.osohq.com/[Oso Slack] 中的开发者社区！
我们非常乐于讨论您的工作并回答你可能遇到的任何问题。
如果你准备开始在你的应用中处理授权，你可以尝试使用 https://www.osohq.com/[Oso] 并可在 https://cloud-docs.osohq.com/[Oso 文档]中了解更多有关信息。
