= 基于角色的访问控制（RBAC）

居于角色的授权，或者基于角色的访问控制，意味着将权限分组到像 “User” 或 “Admin” 之类的角色中，并将这些角色分配给用户。
这是一种组织授权代码通用且有效的方式。
这种结构让你的开发者和用户理解谁可以访问那些资源更容易。

== 系统的那一部分是基于角色的授权

在前面的章节中，我们以 GitClub 为例介绍一个典型的 Web 应用以及如何为其添加授权。
我们证明了授权可以被看作两个部分： *执行* 和 *决定* 。

*决策* 指 “是否允许此用户在这一资源上执行此操作？这一问题” 通常情况下，结果是 “是” 或 “否”。

*执行* 是指我们做出决定后采取的行动。
如果决定是“拒绝”，我们是重定向他们，还是像他们展示一个“Permission Denied”的页面？

在本章中，我们聚焦在 *决策* 上。
特别是，我们会问这样一个问题：“谁可以在应用程序中做什么？”
另外，我们还需要讨论数据 —— 当我们问“谁可以做什么”时，我们正在检查那些数据结构？

为了防止这成为一个完全开放的问题，我们使用授权模型来指导我们的实现。
模型是指导我们实现和组织授权代码结构的方式。

在本章节中，我们将讨论如何使用基于角色的访问控制（RBAC）
我们将围绕几个不同类型的 B2B 应用，介绍几个不同的变体。
对每个模型我们将讨论：

*其授权模型是什么样的* 。
选择正确的授权模型取决于所需的用户体验。
我们将从较高的层次讨论模型所表示的内容，展示其在真实世界的示例，
展示什么时候使用它是有意义的，并描述什么让他非常适合该用例。

*怎样实现此模型* 。
正如我们在上一章谈到的，授权决策由两部分信息构成：数据和逻辑。
授权逻辑决定谁可以做什么的抽象规则集合。
例如，允许一个组织的成员访问属于该组织的仓库。
这些规则通过授权数据进行表示。

我们将另外描述如何构建授权数据来支持我们的逻辑，包括如何将其存储在关系型数据库（例如，PostgreSQL）中的模式图。

在多数情况下，我们将使用上一章介绍的 GitClub 示例应用。
友情提示：GitClub 是一个用于源代码托管、写作以及版本控制的网站，和现实生活中的 GitLab 和 GitHub 类似。
GitClub 提供了一个纯粹的例子来说明最初是什么催生了授权 —— 保护对资源的访问。
在 GitClub 中，一个资源的例子是仓库。
用户可以或不可对仓库进行访问或更改。

=== 实施

对于每个例子，我们将假设授权按照之前的建议在应用中被实施。

例如，处理返回仓库的方法将检查用户是否被允许赌气此仓库，否则返回暂无权限

image::https://assets.website-files.com/5f1483105c9a72fd0a3b662a/606ce858979e452d4761a34e_yzYhfhLkuYb1RCsVVgW9HosrLS05zx9glxDeEzeWB2N5Ufup5gT_Q209VGtrK7UuhGZeb9EvalNZ8ziSGLja-NvZ_wlsYIz9Zx5Z8cp76Y_V5QApQZ0DXuTpNfr0gR3q1OvUd646.png[展示实施授权的应用代码]

We’re using the is_allowed interface introduced in the previous chapter.
我们使用 https://www.eastack.me/blogs/authorization-academy/what-is-authorization.html[上一章] 介绍的 `is_allowed` 接口。

它接受一个 Actor、一个 Action 和 一个 Resource 并返回一个 True/False。

=== 为什么使用授权模型

授权模型有助于应用一些结构到我们之前原本开放的问题：谁可以在我们的应用中做什么。
从实现的角度看这很好 —— 有一个可用的模板很有帮助。
另外，它极大的改善了我们的用户体验。

授权模型不仅指导我们的实现。
这也是在我们向我们的用户展示他们可以在我们的应用中做什么时，教给用户的心智模型。
通过拥有一个清晰的授权模型，我们可以告诉我们的用户，“这是您在我们的应用中预期的权责”。



